### ISSUE TITLE
Wrong PitchTier formats cause crash

### ISSUE THREAD

**Issue by Alexander-kniit** [TUD-STKS/TargetOptimizer#52]
Trying to load a PitchTier file which has been saved using the wrong format (other than written in the manual) will crash the application.

**Comment by nullpunktTUD** [comment]
Any chance this may get fixed soon?

**Comment by alwiTUD** [comment]
Please provide an example PitchTier file which is not working (if possible)

**Comment by nullpunktTUD** [comment]
Sure.

[bad_and_good_file.zip](https://github.com/TUD-STKS/TargetOptimizer/files/8582480/bad_and_good_file.zip)

Here is the same pitch tier exported in two different versions (Windows 10, praat 6.0.43):
- ``bad_file.PitchTier`` was exported using "Save as text file..." and causes an unhandled exception when loaded
- ``good_file.PitchTier`` was exported using "Save as PitchTier spreadsheet file..." and works as expected

**Comment by Alexander-kniit** [comment]
Should be fixed.
